name: 下载

on:
  workflow_dispatch:
    inputs:
      URL:
        type: string
        description: URL
        default: ''
        required: true
      
jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      # input
      URL: ${{ github.event.inputs.URL }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install ktoolbox-pure-py

      - name: Downloading
        continue-on-error: false
        run: |
          mkdir ./images
          cp main.py ./images
          cd images
          python main.py
          rm main.py

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: ./images
          if-no-files-found: error
          retention-days: 90
