name: 下载kemono上的画师文件

on:
  workflow_dispatch:
    inputs:
      URL:
        type: string
        description: URL
        default: ''
        required: true

      EMAIL_ID:
        type: string
        default: ''
        description: email address (use,split email address)
        required: false
      
jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      # input
      URL: ${{ github.event.inputs.URL }}
      EMAIL_ID: ${{ github.event.inputs.EMAIL_ID }}

      #email
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install ktoolbox-pure-py

      - name: Send Email (1/3)
        run: |
          export STATUS=1
          export USER='Name is still geting, place wait for the 3rd part.'
          python email.py

      - name: Downloading
        continue-on-error: false
        run: |
          mkdir ./images
          cp main.py ./images
          cd images
          python main.py
          rm main.py

      - name: Send Email (2/3)
        run: |
          export STATUS='2'
          export USER='Name is still geting, place wait for the 3rd part.'
          python email.py

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.USER }}
          path: ./images
          if-no-files-found: error
          retention-days: 90

      - name: Send Email (3/3)
        run: |
          export STATUS='3'
          python email.py
